name: Django Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          cd tast_manager_project
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup environment variables
        run: |
          echo "config = {" > tast_manager_project/tast_manager_project/config.py
          echo "    'SECRET_KEY': '${{ secrets.SECRET_KEY }}'," >> tast_manager_project/tast_manager_project/config.py
          echo "    'SECRET_1': '${{ secrets.SECRET_1 }}'" >> tast_manager_project/tast_manager_project/config.py
          echo "}" >> tast_manager_project/tast_manager_project/config.py
          cat tast_manager_project/tast_manager_project/config.py  # Output config.py for verification

      - name: Run Django tests
        run: |
          cd tast_manager_app
          python manage.py test
