name: Django Test Workflow

on: 
  pull_request:
    branches:
      - main


jobs:
  test-run:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Make script executable
        run: |
          chmod +x config_setup.sh
        working-directory: ${{ github.workspace }}
      
      - name: Execute script to create config file and setup secrets
        run: |
          ./config_setup.sh
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          cd tast_manager_project
          python manage.py test
